[workspace.package]
version = "5.0.0-rc1"

[workspace]
resolver = "2"
members = [
    "conjure-runtime",
    "conjure-runtime-config",
    "conjure-verification",
    "conjure-verification-api",
]

[profile.release]
debug = 1

[profile.bench]
debug = 1
