[workspace]
members = [
    "conjure-runtime",
    "conjure-runtime-config",
    "conjure-verification",
    "conjure-verification-api",
    "simulation",
]

[patch.crates-io]
hyper = { git = "https://github.com/hyperium/hyper" }
