[workspace.package]
version = "6.1.0"

[workspace]
resolver = "2"
members = [
    "conjure-runtime",
    "conjure-runtime-config",
    "conjure-runtime-wasm-test",
    "conjure-verification",
    "conjure-verification-api",
]

[profile.release]
debug = 1

[profile.bench]
debug = 1

[patch.crates-io]
conjure-error = { git = "https://github.com/palantir/conjure-rust", branch = "conjure-object-js" }
conjure-http = { git = "https://github.com/palantir/conjure-rust", branch = "conjure-object-js" }
conjure-macros = { git = "https://github.com/palantir/conjure-rust", branch = "conjure-object-js" }
conjure-object = { git = "https://github.com/palantir/conjure-rust", branch = "conjure-object-js" }
conjure-serde = { git = "https://github.com/palantir/conjure-rust", branch = "conjure-object-js" }
