[workspace]
members = [
    "conjure-runtime",
    "conjure-runtime-config",
    "conjure-verification",
    "conjure-verification-api",
    "simulation",
]

[profile.release]
debug = 1

[profile.bench]
debug = 1

[patch.crates-io]
tokio = { git = "https://github.com/sfackler/tokio", branch = "deterministic-time" }
