[workspace]
members = [
    "conjure-runtime",
    "conjure-runtime-config",
    "conjure-verification",
    "conjure-verification-api",
]

[patch.crates-io]
hyper = { git = "https://github.com/sfackler/hyper", branch = "connected-accessors" }
