[workspace]
members = [
    "conjure-runtime",
    "conjure-runtime-config",
    "conjure-verification",
    "conjure-verification-api",
    "simulation",
]

[profile.release]
debug = 1

[profile.bench]
debug = 1

[patch.crates-io]
conjure-http = { git = "https://github.com/palantir/conjure-rust", branch = "float-keys" }
conjure-error = { git = "https://github.com/palantir/conjure-rust", branch = "float-keys" }
conjure-object = { git = "https://github.com/palantir/conjure-rust", branch = "float-keys" }
conjure-serde = { git = "https://github.com/palantir/conjure-rust", branch = "float-keys" }
conjure-codegen = { git = "https://github.com/palantir/conjure-rust", branch = "float-keys" }
