[package]
name = "conjure-runtime-wasm-test"
edition = "2024"
version.workspace = true
publish = false

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
bytes = "1.10.1"
conjure-http = "4.10"
conjure-runtime = { path = "../conjure-runtime" }
futures-util = "0.3.31"
http = "1"
wasm-bindgen-test = "0.3.50"
